# Generated by Django 5.0 on 2025-11-19 19:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TallerMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del taller mecánico', max_length=150)),
                ('direccion', models.CharField(help_text='Dirección completa del taller', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, help_text='Latitud geográfica del taller', max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, help_text='Longitud geográfica del taller', max_digits=9)),
                ('horario', models.CharField(blank=True, help_text='Horario de atención (ej: Lun-Vie 8:00-18:00)', max_length=100, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('calificacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calificación del taller (0.00 a 5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('servicios', models.TextField(blank=True, help_text='Descripción de servicios ofrecidos (separados por comas)', null=True)),
                ('verificado', models.BooleanField(default=False, help_text='Indica si el taller ha sido verificado por el sistema')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el taller está activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Taller Mecánico',
                'verbose_name_plural': 'Talleres Mecánicos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['latitud', 'longitud'], name='vehiculos_t_latitud_b0f3f2_idx'), models.Index(fields=['nombre'], name='vehiculos_t_nombre_a0e7c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa o matrícula del vehículo', max_length=20, unique=True)),
                ('marca', models.CharField(help_text='Marca del vehículo (ej: Toyota, Ford, Honda)', max_length=50)),
                ('modelo', models.CharField(help_text='Modelo del vehículo (ej: Corolla, F-150)', max_length=50)),
                ('año', models.IntegerField(help_text='Año de fabricación', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('tipo', models.CharField(choices=[('AUTO', 'Automóvil'), ('MOTO', 'Motocicleta'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión'), ('VAN', 'Van')], default='AUTO', max_length=20)),
                ('kilometraje', models.IntegerField(default=0, help_text='Kilometraje actual del vehículo', validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie o VIN', max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('propietario_nombre', models.CharField(help_text='Nombre del propietario', max_length=100)),
                ('propietario_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('propietario_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en el sistema')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el vehículo está activo en el sistema')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el vehículo', null=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['placa'], name='vehiculos_v_placa_4999e1_idx'), models.Index(fields=['marca', 'modelo'], name='vehiculos_v_marca_38767a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Mantenimiento Correctivo'), ('REVISION', 'Revisión General'), ('REPARACION', 'Reparación')], default='PREVENTIVO', max_length=20)),
                ('titulo', models.CharField(help_text='Título o resumen del mantenimiento', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del mantenimiento realizado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_programada', models.DateField(blank=True, help_text='Fecha programada para el mantenimiento', null=True)),
                ('fecha_realizado', models.DateField(blank=True, help_text='Fecha en que se realizó el mantenimiento', null=True)),
                ('kilometraje_realizado', models.IntegerField(help_text='Kilometraje del vehículo al momento del mantenimiento', validators=[django.core.validators.MinValueValidator(0)])),
                ('proximo_kilometraje', models.IntegerField(blank=True, help_text='Kilometraje sugerido para próximo mantenimiento', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo total del mantenimiento', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('piezas_reemplazadas', models.TextField(blank=True, help_text='Lista de piezas que fueron reemplazadas', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('taller', models.ForeignKey(blank=True, help_text='Taller donde se realizó el mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='vehiculos.tallermecanico')),
                ('vehiculo', models.ForeignKey(help_text='Vehículo al que se le realizó el mantenimiento', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_realizado', '-fecha_programada'],
                'indexes': [models.Index(fields=['vehiculo', 'fecha_realizado'], name='vehiculos_m_vehicul_fbe672_idx'), models.Index(fields=['estado'], name='vehiculos_m_estado_7b6a1e_idx'), models.Index(fields=['tipo'], name='vehiculos_m_tipo_4a7109_idx')],
            },
        ),
    ]
